### ISSUE TITLE
p-tsanev - LiquidityBorrowingManager.sol#takeOverDebt() - wrong key used when pushing loans to the new borrow

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-real-wagmi-judging#11]
p-tsanev

high

# LiquidityBorrowingManager.sol#takeOverDebt() - wrong key used when pushing loans to the new borrow
## Summary
The ``takeOverDebt()`` function is supposed, upon met criteria, to transfer a borrowing to a different owner, by creating a new borrowing key for the mapping and passing the old loans to the new borrow struct. There is a critical flaw in this functionality, that would not allow for correct overtaking.

## Vulnerability Detail
The function updates the old borrow's fees up to the moment of taking over and then generates a new key and a new borrow struct. However, when the function ``_addKeysAndLoansInfo`` is invoked to transfer the old loans to the new key, instead of the ``newBorrowingKey``, the old ``borrowingKey`` variable is passed instead.
This would lead to old loans being pushed again in the array for the old key, potentially reverting on exceeding the maximum allowed loans per positions.
Taking over would not be possible in such cases.

## Impact
Impossible to take over loans, which is a core functionality of the protocol

## Code Snippet
https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L431-L441

## Tool used

Manual Review

## Recommendation
Pass the correct value to the function as such:
``_addKeysAndLoansInfo(newBorrowing.borrowedAmount > 0, newBorrowingKey, oldLoans)``

Duplicate of #53

**Comment by fann95** [comment]
This is an inattention error related to the accelerated development of the project. I think we would have fixed this during testing, but thanks for the hint anyway. We will fix it.
