### ISSUE TITLE
pks_ - Wrong uniswap v3 amountOut cause user attacked by MEV and lose funds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-real-wagmi-judging#117]
pks_

high

# Wrong uniswap v3 amountOut cause user attacked by MEV and lose funds
## Summary

uniswap v3 amountOutMinimum is set to 0 in `v3SwapExactInputParams`, it means no slippage protection could cause user loss funds. 

## Vulnerability Detail

When user borrow token from protocol, the call trace is below:

`LiquidityBorrowingManager#borrow -> LiquidityBorrowingManager#_precalculateBorrowing -> LiquidityBorrowingManager#_v3SwapExactInput -> IUniswapV3Pool#swap`, the `amountOutMinimum` parameter is set to 0 here which could attacked by MEV and lose funds. 

## Impact

User could lose funds when borrow tokens from protocol.

## Code Snippet

https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L886-L894

https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/abstract/ApproveSwapAndPay.sol#L204-L226

## Tool used

vscode, Manual Review

## Recommendation

Set `amountOutMinimum` by user input or set a reasonable value here.

**Comment by yuliyu123** [comment]
Escalate

This scenery has no slippage protection based on the context, the `amountOut` in _v3SwapExactInput could be a very low value and cause users to lose funds, please double-check it.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This scenery has no slippage protection based on the context, the `amountOut` in _v3SwapExactInput could be a very low value and cause users to lose funds, please double-check it.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Czar102** [comment]
I think the check is [right after](https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L898-L901). Is this right?

**Comment by talfao** [comment]
Yes.

**Comment by Czar102** [comment]
Planning to reject the escalation and leave issue as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yuliyu123](https://github.com/sherlock-audit/2023-10-real-wagmi-judging/issues/117/#issuecomment-1786346824): rejected
