### ISSUE TITLE
kaysoft - Use of UniswapV3 slot0() function to get sqrtPriceLimitX96 can lead to price manipulation.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-10-real-wagmi-judging#18]
kaysoft

high

# Use of UniswapV3 slot0() function to get sqrtPriceLimitX96 can lead to price manipulation.
## Summary
The UniswapV3 slot0() function is used to get the sqrtPriceX96 as shown below.
```solidity
function _getCurrentSqrtPriceX96(
        bool zeroForA,
        address tokenA,
        address tokenB,
        uint24 fee
    ) private view returns (uint160 sqrtPriceX96) {
        if (!zeroForA) {
            (tokenA, tokenB) = (tokenB, tokenA);
        }
        address poolAddress = computePoolAddress(tokenA, tokenB, fee);
        (sqrtPriceX96, , , , , , ) = IUniswapV3Pool(poolAddress).slot0();//@audit prone to price manipulation search slot0
    }
```

## Vulnerability Detail
The _getCurrentSqrtPriceX96(...) function above is used in _getHoldTokenAmountIn to calculate values which were used for swap here: https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L229-L308

LINK TO THE UNISWAP SLOT0 FUNCTION USED TO GET sqrtPriceX96
- https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L341
- https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L507

## Impact
Using Uniswap's slot0 function to get sqrtPriceX96 can be manipulated which will cause loss of asset for the user.

## Tool used
Manual Review

## Recommendation
Use the TWAP to get the value of sqrtPriceX96

## Reference
- [Similar Report on Code4rena](https://code4rena.com/reports/2023-05-maia#h-02-use-of-slot0-to-get-sqrtpricelimitx96-can-lead-to-price-manipulation)

Duplicate of #109

**Comment by fann95** [comment]
We need to know the proportion of tokens on the current sqrtPriceX96 to restore the liquidity, so therefore in this case, nothing other than slot0 will be suitable.
