### ISSUE TITLE
kaysoft - Slippage loss because `amount0Min` and `amount1Min` are set to zero

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-real-wagmi-judging#19]
kaysoft

high

# Slippage loss because `amount0Min` and `amount1Min` are set to zero
## Summary
Setting `amount0Min` and `amount1Min` for increasing and adding liquidity can result in loss of funds due to sandwich attack.
- https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L356-L357
- https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L403-L404

## Vulnerability Detail
`amount0Min` and `amount1Min` are set to zero in the links below which indicates that the user is okay with 100% slippage loss. The only check done afterwards is to check that amount received are not zero which can be bypassed by allowing user receive just tiny amount of asset.

```solidity
 INonfungiblePositionManager.DecreaseLiquidityParams({
                tokenId: tokenId,
                liquidity: liquidity,
                amount0Min: 0, //@audit sliipage loss. 
                amount1Min: 0,
                deadline: block.timestamp//@audit deadline.
            })
```
```solidity
 INonfungiblePositionManager.IncreaseLiquidityParams({
                tokenId: loan.tokenId,
                amount0Desired: amount0,
                amount1Desired: amount1,
                amount0Min: 0,
                amount1Min: 0,//@audit slippage loss
                deadline: block.timestamp
            })
```
## Impact
Loss of fund due to slippage

## Code Snippet
```solidity
 INonfungiblePositionManager.IncreaseLiquidityParams({
                tokenId: loan.tokenId,
                amount0Desired: amount0,
                amount1Desired: amount1,
                amount0Min: 0,
                amount1Min: 0,//@audit slippage loss
                deadline: block.timestamp
            })
```

## Tool used
Manual Review

## Recommendation
Allow `amount0Min` and `amount1Min` to be passed as input parameter offchain.

**Comment by talfao** [comment]
Escalate

This issue is not a duplicate of #103. Furthermore, this issue should be invalid.

As the sponsor states, during the increase of liquidity, there is a following check if the restored liquidity matches loan liquidity. (https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L408-L427)
```
   if (restoredLiquidity < loan.liquidity) {
            // Get the balance of holdToken and saleToken
...
```
For decreased liquidity, the params for slippage control are implemented in the _preCaulculateBorrowing by checking if `holdTokenBalance` is more or equal to `minHoldTokenOut`

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue is not a duplicate of #103. Furthermore, this issue should be invalid.
> 
> As the sponsor states, during the increase of liquidity, there is a following check if the restored liquidity matches loan liquidity. (https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L408-L427)
> ```
>    if (restoredLiquidity < loan.liquidity) {
>             // Get the balance of holdToken and saleToken
> ...
> ```
> For decreased liquidity, the params for slippage control are implemented in the _preCaulculateBorrowing by checking if `holdTokenBalance` is more or equal to `minHoldTokenOut`

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by kayroy247** [comment]
First there are multiple ways to interact with Uniswap and most of them require slippage protection.
Examples are:
1. increaseLiquidity 
2. decreaseLiquidity
3. Swap
All interactions above requires slippage protection to avoid sandwich attack so the minimum acceptable amount is stated if not, the transaction should revert. 
Setting zero as minimum amount during any of these operations means the caller accepts zero as the minimum amount for a successful swap. Bots take advantage of txs like this and sandwich it for profit.

I think the difference is that I noted slipage protection  for `increaseLiquidity` and `decreaseLiquidity` but some people noted slippage protection for only the `swap` action. What the sponsor pointed out as slippage protection was just for the `swap` action. No slippage protection during `decreaseLiquidity` here.
- https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L349-L376
```solidity
 function _decreaseLiquidity(uint256 tokenId, uint128 liquidity) private {
        // Call the decreaseLiquidity function of underlyingPositionManager contract
        // with DecreaseLiquidityParams struct as argument
        (uint256 amount0, uint256 amount1) = underlyingPositionManager.decreaseLiquidity(
            INonfungiblePositionManager.DecreaseLiquidityParams({
                tokenId: tokenId,
                liquidity: liquidity,
                amount0Min: 0,
                amount1Min: 0,
                deadline: block.timestamp
            })
        );
        // Check if both amount0 and amount1 are zero after decreasing liquidity
        // If true, revert with InvalidBorrowedLiquidity exception
        if (amount0 == 0 && amount1 == 0) {
            revert InvalidBorrowedLiquidity(tokenId);
        }
        // Call the collect function of underlyingPositionManager contract
        // with CollectParams struct as argument
        (amount0, amount1) = underlyingPositionManager.collect(
            INonfungiblePositionManager.CollectParams({
                tokenId: tokenId,
                recipient: address(this),
                amount0Max: uint128(amount0),
                amount1Max: uint128(amount1)
            })
        );
    }
```
The uniswap decreaseLiquidity is called with 0 amount0Min and zero amount1Min. The only check that followed was to check if amount received are zero. So in this case the returned amount can be just 1 wei both after the sandwich attack.

**Comment by Czar102** [comment]
Hey @talfao thanks for the escalation. Can you link the code which checks slippage for decreasing liquidity?

**Comment by talfao** [comment]
@Czar102 
Here -> https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L899
And this  -> https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L493

You do not care about slippage in restore liqudity and following swaps for soldToken. As you just care about how much hold Token was restored => and there is a check for that.

And how much difference of borrowed amount and obtained hold token, you are willing to pay.

**Comment by Czar102** [comment]
Planning to accept the escalation and make this issue invalid.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [talfao](https://github.com/sherlock-audit/2023-10-real-wagmi-judging/issues/19/#issuecomment-1788074677): accepted
