### ISSUE TITLE
jonatascm - Solidity version not run in all chains

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-10-real-wagmi-judging#4]
jonatascm

high

# Solidity version not run in all chains
## Summary

The Solidity version 0.8.21 includes the push0 instruction, which is not supported in some chains, such as [[Arbitrum](https://docs.arbitrum.io/solidity-support)](https://docs.arbitrum.io/solidity-support).

## Vulnerability Detail

In newer versions of Solidity, the push0 instruction is included. However, some chains do not support this instruction. The Real Wagmi should be deployed on multiple chains. However, some of them do not support the push0 instruction. This means that the contract will be deployed but will not be executed.

## Impact

Code deployed in not supported chains will not execute.

## Code Snippet

In all files the solidity version is set to 0.8.21

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.21;
```
https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L2
https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/Vault.sol#L2

## Tool used

Manual Review

## Recommendation

Downgrade the version of solidity for deployment.

Duplicate of #84

**Comment by fann95** [comment]
solidity version 0.8.20 or higher can be used in such chains with an evm-version lower than the default shanghai
