### ISSUE TITLE
IceBear - LiquidityManager.sol _increaseLiquidity() lacks slippage protection

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-real-wagmi-judging#55]
IceBear

medium

# LiquidityManager.sol _increaseLiquidity() lacks slippage protection
## Summary
LiquidityManager.sol _increaseLiquidity() lacks slippage protection 
## Vulnerability Detail
In below instances, a call to Uniswap V3 is made. Calls amount0Min and amount1Min are each set to 0, which allows for a 100% slippage tolerance. This means, that the action could lead to the caller losing up to 100% of their tokens due to slippage.
https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L403-L404
similar finding:
https://code4rena.com/reports/2023-05-maia#m-18-a-lack-of-slippage-protection-can-lead-to-a-significant-loss-of-user-funds
## Impact
There is no slippage protection on any of the calls to increase or decrease liquidity, allowing for trades to be subject to MEV-style attacks such as front-running and sandwiching.
## Code Snippet
https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L403-L404
## Tool used

Manual Review

## Recommendation
allow the caller to specify values for amount0Min and amount1Min instead of setting them to 0.

**Comment by talfao** [comment]
Escalate

Invalid. Same reason as in #19

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Invalid. Same reason as in #19 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Czar102** [comment]
Same as in #19, planning to accept the escalation and make this issue invalid.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [talfao](https://github.com/sherlock-audit/2023-10-real-wagmi-judging/issues/55/#issuecomment-1788077442): accepted
