### ISSUE TITLE
Bauer - Attacker can manipulate low TVL Uniswap V3 pool to swap to make user in loss

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-real-wagmi-judging#63]
Bauer

high

# Attacker can manipulate low TVL Uniswap V3 pool to swap to make user in loss
## Summary
Uniswap V3 can have multiple pools for the same pairs of ERC20 tokens with different fee params,positions in low-liquidity pools may lead to losses for users.

## Vulnerability Detail
Uniswap V3 can have multiple pools for the same pairs of ERC20 tokens with different fee params. A fews has most the liquidity, while other pools have extremely little TVL or even not created yet. Attackers can abuse it, create low TVL pool where liquidity in this pool mostly (or fully) belong to attacker’s position, malicious actors can offer their positions to borrowers for lending. Borrowers then perform swaps and liquidity additions within the pool, potentially resulting in capital losses.

## Impact
Users may incur losses.

## Code Snippet
https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L465-L516

## Tool used

Manual Review

## Recommendation
Consider implementing a whitelist that only allows positions from pools with a sufficient Total Value Locked (TVL) to be part of the protocol

**Comment by talfao** [comment]
Escalate

This issue is not duplicate #109 as it does not mention any usage of slot0 or dynamic slippage params. Furthermore, it seems invalid as it does not describe any issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue is not duplicate #109 as it does not mention any usage of slot0 or dynamic slippage params. Furthermore, it seems invalid as it does not describe any issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Czar102** [comment]
Agree, planning to accept the escalation and invalidate the issue.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [talfao](https://github.com/sherlock-audit/2023-10-real-wagmi-judging/issues/63/#issuecomment-1788102371): accepted

**Comment by sleepriverfish** [comment]
Escalate

**Comment by sleepriverfish** [comment]
Escalate
It is the same as the question above.https://github.com/code-423n4/2022-11-paraspace-findings/issues/407

**Comment by talfao** [comment]
@sleepriverfish you can not escalate now, it is almost one week after this period.

Furthermore, your issue does not specify any attack path and problem for the protocol. And I think there is not any in the case of this borrowing design.
