### ISSUE TITLE
seeques - Collateral sent during borrowing is lost due to not accounting for borrowingCollateral in borrowing.DailyRateCollateralBalance

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-real-wagmi-judging#67]
seeques

high

# Collateral sent during borrowing is lost due to not accounting for borrowingCollateral in borrowing.DailyRateCollateralBalance
## Summary
During borrowing, a borrower has to pay some collateral in holdToken plus deposit for holding a position for 24 hours, which is a product of the `borrowedAmount` and the `currentDailyRate`. The latter is added to the collateral balance of the borrower, while the former is not. This makes the collateral stuck in the Vault.
## Vulnerability Detail
In the [`borrow()`](https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L488-L503) function only the `dailyRateCollateral` is added to the `borrowing.DailyRateCollateralBalance`, while both `dailyRateCollateral` and `borrowingCollateral` are transferred to the system.

`borrowing.DailyRateCollateralBalance` is the collateral balance before fees accrual and it is used to determine if a loan is liquidatable or not by calculating the actual collateral balance of the loan (that is, collateral balance minus the fees accrued).
```solidity
            (collateralBalance, currentFees) = _calculateCollateralBalance(
                borrowing.borrowedAmount,
                borrowing.accLoanRatePerSeconds,
                borrowing.dailyRateCollateralBalance,
                accLoanRatePerSeconds
            );
```
The only way of retrieving collateral from the Vault is calling the `repay()` function which can be called is case of liquidation or closing a position by the borrower.

[In case of liquidation](https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L573-L578) (i.e., when `borrowing.DailyRateCollateralBalance` minus the fees < 0), the `borrowing.DailyRateCollateralBalance` is added to borrowing.feesOwed after which tokens are transferred from the Vault and liquidity is being restored in uniswap position [in the call](https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L650-L660) to `_restoreLiquidity()`, [during which](https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L306-L315) fees owed to a position owner is also transferred from the Vault.

[In case of closing position](https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L565-L572) by the borrower the same happens, only his `borrowing.DailyRateCollateralBalance` is applied not to borrowing.feesOwed, but to the liquidationBonus which he receives at the end of the call.

There is [a 3rd case of emergency closure](https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L620-L624) by the uniswap position owner but it is the same in a sense that no more tokens are drawn from the Vault that are borrowed and owed.

This means that the `borrowingCollateral` which is transferred upon borrowing is lost in the system.
## Impact
Loss of funds.
## Code Snippet
https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L488-L490
https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L492-L503
https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L552-L557
https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/abstract/DailyRateAndCollateral.sol#L103-L118
## Tool used

Manual Review

## Recommendation
Add borrowing collateral to the collateral balance
```solidity
borrowing.dailyRateCollateralBalance +=
            (cache.dailyRateCollateral *
            Constants.COLLATERAL_BALANCE_PRECISION) + (borrowingCollateral * Constants.COLLATERAL_BALANCE_PRECISION);
```

**Comment by seeques** [comment]
Escalate

As the code suggests, both `borrowedAmount` and `borrowingCollateral` are included into `holdTokenBalance` (as per #86). `borrowedAmount` [is calculated as a single-sided position](https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L116-L140) and `holdTokenBalance` is the **borrowedAmount + swapped saleTokens**. If the position is in the current tick range, only those holdTokens would be a part of `borrowedAmount` which were extracted from the position BEFORE swap was made, and those holdTokens that were received through swapping would not be accredited to anything in the system and they would be lost.

At first I thought that `borrowingCollateral` was this missing part of holdTokens that were swapped and which were not attributed to the `borrowedAmount`. I understand now that the `borrowingCollateral` is the margin deposit and that it should have been included in the `borrowedAmount` as per design. Hovewer, as per case explained above, the holdTokens that were swapped should be added to `borrowedAmount` still. Otherwise, the restoredLiquidity would be [lower](https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L410) than the `liquidity.loan`, the repayment would revert and tokens would be stuck in the vault.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> As the code suggests, both `borrowedAmount` and `borrowingCollateral` are included into `holdTokenBalance` (as per #86). `borrowedAmount` [is calculated as a single-sided position](https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L116-L140) and `holdTokenBalance` is the **borrowedAmount + swapped saleTokens**. If the position is in the current tick range, only those holdTokens would be a part of `borrowedAmount` which were extracted from the position BEFORE swap was made, and those holdTokens that were received through swapping would not be accredited to anything in the system and they would be lost.
> 
> At first I thought that `borrowingCollateral` was this missing part of holdTokens that were swapped and which were not attributed to the `borrowedAmount`. I understand now that the `borrowingCollateral` is the margin deposit and that it should have been included in the `borrowedAmount` as per design. Hovewer, as per case explained above, the holdTokens that were swapped should be added to `borrowedAmount` still. Otherwise, the restoredLiquidity would be [lower](https://github.com/sherlock-audit/2023-10-real-wagmi/blob/b33752757fd6a9f404b8577c1eae6c5774b3a0db/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L410) than the `liquidity.loan`, the repayment would revert and tokens would be stuck in the vault.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Czar102** [comment]
@cvetanovv @fann95 what do you think?

**Comment by fann95** [comment]
> and holdTokenBalance is the borrowedAmount + swapped saleTokens. 

This is incorrect. holdTokenBalance - these are the tokens received during liquidity extraction (including the result of the swap). 
borrowedAmount = holdTokenBalance+marginDeposit
borrowedAmount is the maximum amount calculated on the border of the position range(single mode).

**Comment by seeques** [comment]
Hi @fann95 
Yes, excuse me for this confusion. My main point is that nowhere in the code this part of holdTokenBalance that was received as the result of the swap is added to borrowedAmount, which makes the borrowedAmount less than intended.

**Comment by fann95** [comment]
It should not be added, it is part of borrowedAmount. That is, this is what you actually received. borrowedAmount.will be more than holdTokenBalance or equal if the position is outside the current tick and swap will not occur

**Comment by seeques** [comment]
If the position is outside, that is correct. But if the position is inside the current tick range, which would be in 90% of the cases, and the swap will occur, these swapped tokens are just sent to the Vault, where they would be stuck and lost as they are not represented anywhere in the system, which is a loss of liquidity for LPs.

**Comment by fann95** [comment]
> If the position is outside, that is correct. But if the position is inside the current tick range, which would be in 90% of the cases, and the swap will occur, these swapped tokens are just sent to the Vault, where they would be stuck and lost as they are not represented anywhere in the system, which is a loss of liquidity for LPs.


No, these exchanged tokens are part of the borrowedAmount . Because if the position is inside a tick, the result of extracted+swaped tokens will be less than the borrowedAmount.  extracted+swaped+marginDeposit=borrowedAmount (which is stored)

**Comment by seeques** [comment]
`borrowedAmount` is calculated single-sidedly (only as amount0 or amount1, depending on the zeroForSaleToken flag):
```solidity
                // Calculate borrowed amount
                borrowedAmount += _getSingleSideRoundUpBorrowedAmount(
                    zeroForSaleToken,
                    tickLower,
                    tickUpper,
                    liquidity
```
```solidity
        borrowedAmount = (
            zeroForSaleToken
                ? LiquidityAmounts.getAmount1ForLiquidity(
                    TickMath.getSqrtRatioAtTick(tickLower),
                    TickMath.getSqrtRatioAtTick(tickUpper),
                    liquidity
                )
                : LiquidityAmounts.getAmount0ForLiquidity(
                    TickMath.getSqrtRatioAtTick(tickLower),
                    TickMath.getSqrtRatioAtTick(tickUpper),
                    liquidity
                )
        );
```
But both amount0 and amount1 are borrowed from LP's position during liquidity extraction if the position is in the current tick range. Hence my reasoning that those tokens are not part of the `borrowedAmount`.
Moreover, my issue #86, which is deemed valid and was confirmed by you, also explains why borrowedAmount in this case is less than extracted+swapped

**Comment by fann95** [comment]
Probably such a fantastic case is possible with positive slippage when the extracted+swaped  tokens will be slightly more than the borrowedAmount, but in this case this dust will remain on the contract and it will be taken by the first one who calls the repay. We did not process these cases because they are unlikely and we wouldn't want to complicate the code and waste extra gas. The number of tokens in the single-side position will be more than on the current tick even if you exchange the second token.The price of a token will be worse in single positions.That is why borrowedAmount  is calculated at the worst price that can be.  I accepted [#86](https://github.com/sherlock-audit/2023-10-real-wagmi-judging/issues/86) problem since it was possible to get DOS simply by sending a small number of tokens to the contract.
 P.S. It would be great to receive more tokens when extracting liquidity on the current tick than after extracting in a single position.))

**Comment by Czar102** [comment]
@seeques would you agree with the above?

@fann95 can you elaborate on what do you mean by "positive slippage" and "dust"? Does "dust" imply that the loss is constrained to a small amount? In what way?

**Comment by seeques** [comment]
Yes, I agree. I would argue though that any dust would not remain in the contract, but as a part of holdTokenBalance would be transferred to the Vault. And upon repayment this dust would not be taken as it would not be tranferred back to the contract from the Vault.

**Comment by Czar102** [comment]
@seeques does it mean that this behavior doesn't present a high/medium severity issue?

**Comment by seeques** [comment]
It does not. I misinterpreted initially amounts calculation, but now I can see where my problem was.

**Comment by Czar102** [comment]
Great that consensus has been achieved. Will be rejecting the escalation and keeping the issue invalid.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [seeques](https://github.com/sherlock-audit/2023-10-real-wagmi-judging/issues/67/#issuecomment-1786941088): accepted
