### ISSUE TITLE
0x52 - Slippage controls inside _restoreLiqudity are ineffective allowing repay() calls to be sandwiched and all profits stolen

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-real-wagmi-judging#79]
0x52

medium

# Slippage controls inside _restoreLiqudity are ineffective allowing repay() calls to be sandwiched and all profits stolen
## Summary

When repaying a loan, the user repaying is required to restore the borrowed liquidity to each LP. This is done via swapping the hold to swap token, then using these funds to reconstruct the LP. To establish the `amountOutMinimum` the contract first makes a call to the QuoterV2. Due to the relative nature of this call, it provides no protection against sandwich attacks.

## Vulnerability Detail

[LiquidityManager.sol#L246-L266](https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L246-L266)

    uint256 saleTokenAmountOut;
    (saleTokenAmountOut, cache.sqrtPriceX96, , ) = underlyingQuoterV2
        .quoteExactInputSingle(
            IQuoterV2.QuoteExactInputSingleParams({
                tokenIn: cache.holdToken,
                tokenOut: cache.saleToken,
                amountIn: holdTokenAmountIn,
                fee: params.fee,
                sqrtPriceLimitX96: 0
            })
        );
  
    // Perform external swap if external swap target is provided
    if (externalSwap.swapTarget != address(0)) {
        _patchAmountsAndCallSwap(
            cache.holdToken,
            cache.saleToken,
            externalSwap,
            holdTokenAmountIn,
            (saleTokenAmountOut * params.slippageBP1000) / Constants.BPS
        );

When making a swap, saleTokenAmountOut is first calculated by making a call to QuoterV2. This simulates the transaction directly on the target pool. This is the fundamental problem with this design. If the pool being utilized is sandwich attacked then the expected out will also fall. This creates a larger slippage than intended allowing all user profit to be stolen.

Example:
Assume a user is closing their position and the current price of ETH is $1600. The user is inputs a reasonable max slippage of 1%. This means the lowest price the user should get is $1584. However, this is not the case. Instead assume that an attacker is observing the mempool. They see the transaction and sandwich attack it. First the sell ETH into the pool lowering the price to $1500. When the user's transaction executes, QuoterV2 will quote the price of ETH as $1500 and therefore the minimum price for the user is now $1485.

## Impact

User repayments can be sandwich attacked due to ineffective slippage controls

## Code Snippet

[LiquidityManager.sol#L223-L321](https://github.com/sherlock-audit/2023-10-real-wagmi/blob/main/wagmi-leverage/contracts/abstract/LiquidityManager.sol#L223-L321)

## Tool used

Manual Review

## Recommendation

Allow the user to specify an min/max `sqrtPriceLimitX96`. If the pool ever goes above/below that value then revert the call.

Duplicate of #109

**Comment by fann95** [comment]
this is a duplicate of this one https://github.com/sherlock-audit/2023-10-real-wagmi-judging/issues/109
